spring:
  application:
    name: APIGATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: head-service
          uri: lb://HEAD-SERVICE
          predicates:
            - Path=/hotel/**
          
        - id: registration-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**
          
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
                  



server:
  port: 8888

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream

